services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 8080:8080
      - 9000:9000
    restart: unless-stopped
    networks:
      - app

networks:
  app:
    driver: bridge
